version: '3.1'

services:
    actuacion-clase:
      image: httpd:2.4
      ports: 
        - 8080:80
      volumes:
        - C:\\Users\Martin\docker\actuacion-clase\website:/usr/local/apache2/htdocs/